# .pre-commit-config.yaml
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            "langgraph",
            "langchain-openai",
            "wandb",
            "sentence-transformers",
            "datasets",
            "numpy",
            "pandas",
            "pytest"
        ]
